# Generated by Django 3.0.2 on 2020-01-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200120_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='address',
        ),
    ]
